### ISSUE TITLE
Add Metrics for Shepherd 

### ISSUE THREAD

**Issue by taddes** [mozilla-services/consvc-shepherd#125]
As part of being able to verify application stability and performance, we want to add metrics to Shepherd. Given we are moving to a model of Continuous Integration and Continuous Deployment, we want to have automated telemetry we can depend on to know the state of Shepherd at any time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2411)

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Duplicate
