### ISSUE TITLE
ADR for Markus Metrics Library

### ISSUE THREAD

**Issue by taddes** [mozilla-services/consvc-shepherd#136]
Create an ADR to capture the benefits and decision behind using Markus as our metrics client library, as discussed by the team and sourced from other Mozilla teams. Can be used for future reference given the possibility of using the library on other projects.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2431)

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Duplicate ofhttps://mozilla-hub.atlassian.net/browse/DISCO-2427 ( https://mozilla-hub.atlassian.net/browse/DISCO-2427|smart-link )
