### ISSUE TITLE
Authentication for Shepherd

### ISSUE THREAD

**Issue by tiftran** [mozilla-services/consvc-shepherd#26]
Once we have  "real"/non dev instance for Shepherd, authentication will be needed. 
Relation between gcp IAM, LDAP and django users will to be connected somehow...

We might want to do something similar to [experimenter](https://github.com/mozilla/experimenter/commit/dd1db67b0bd13a61fb2850d612ced76d06e0730d)

This will require help from SRE.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1731)

**Comment by data-sync-user** [comment]
➤ Ron Manning commented:

Waiting on SRE to have the bandwidth to get it deployed.

**Comment by data-sync-user** [comment]
➤ Tif Tran commented:

Related PRs:

https://github.com/mozilla-services/consvc-shepherd/pull/44 ( https://github.com/mozilla-services/consvc-shepherd/pull/44|smart-link )
https://github.com/mozilla-services/consvc-shepherd/pull/66 ( https://github.com/mozilla-services/consvc-shepherd/pull/66|smart-link )
https://github.com/mozilla-services/consvc-shepherd/pull/69 ( https://github.com/mozilla-services/consvc-shepherd/pull/69|smart-link )

Tested on https://shepherd-dev.topsites.nonprod.cloudops.mozgcp.net/admin/ ( https://shepherd-dev.topsites.nonprod.cloudops.mozgcp.net/admin/ ) with myself and Nan as users. Auth is working
