### ISSUE TITLE
Look into improving UI by having multiple paths per domain

### ISSUE THREAD

**Issue by tiftran** [mozilla-services/consvc-shepherd#27]
-  For a given host there can be multiple paths
-  for each path there should be a value and a matching value
-  Take note this will be tricky on the UI side as Django admin only allows one level of nesting and might not be worth pursuing?, there are existing external libraries, would need to look into how well maintain they are before deciding to use them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1734)

**Comment by data-sync-user** [comment]
➤ Tif Tran commented:

not worth pursuing
