### ISSUE TITLE
Add validation to publish_snapshot to only publish unlaunched snapshots

### ISSUE THREAD

**Issue by tiftran** [mozilla-services/consvc-shepherd#30]
dependent on #29 

Publishing a "launched" snapshot would result in overwriting the launch date.
Instead we should show an error message stating that the settings has already been previously published.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1737)

**Comment by ddurst** [comment]
So does this mean that, once published, a snapshot cannot be published again?
