### ISSUE TITLE
CSRF verification failed on shepherd-dev.topsites.nonprod.cloudops.mozgcp.net

### ISSUE THREAD

**Issue by tiftran** [mozilla-services/consvc-shepherd#56]
We encounter this
<img width="1158" alt="Screen Shot 2022-10-17 at 8 20 56 PM" src="https://user-images.githubusercontent.com/25379936/196328024-8f65cb0d-b1c4-4be6-95a1-4d9ae21160c7.png">

when trying to submit a form

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-2043)

**Comment by data-sync-user** [comment]
➤ Tif Tran commented:

https://github.com/mozilla-services/consvc-shepherd/pull/57 ( https://github.com/mozilla-services/consvc-shepherd/pull/57|smart-link )
